idam:
  messaging:
    useTopics: false
    subscription:
      add-user: idam-add-user
      modify-user: idam-modify-user
      remove-user: idam-remove-user

spring:
  jms:
    servicebus:
      enabled: false
  artemis:
    mode: embedded
    embedded:
      enabled: true
